# The URL the site will be built for
base_url = "https://cybar.dev"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

author = "cybardev"
title = "Cy | Space"
description = "A home for my thoughts"
compile_sass = true
minify_html = true
generate_feeds = true
exclude_paginated_pages_in_sitemap = "all"
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
render_emoji = true
lazy_async_image = true
insert_anchor_links = "heading"

[markdown.highlighting]
style = "class"
light_theme = "kanagawa-lotus"
dark_theme = "kanagawa-dragon"

[extra]
# Put all your custom variables here
