site_url: "https://cybar.dev"
logo:
  src: "https://cybar.dev/assets/images/favicon.ico"
  show_in_header: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
backend:
  name: github
  branch: main
  repo: "cybardev/cybardev.github.io"
  base_url: "https://oauth.cybar.dev"
  commit_messages:
    create: "{{collection}}: add {{slug}}"
    update: "{{collection}}: edit {{slug}}"
    delete: "{{collection}}: remove {{slug}}"
    uploadMedia: "media: add {{path}}"
    deleteMedia: "media: remove {{path}}"
media_folder: "static/assets/images/blog"
public_folder: "/assets/images/blog"
media_libraries:
  all:
    transformations:
      raster_image:
        format: webp
        quality: 96
      svg:
        optimize: true
  cloudflare_r2:
    bucket: media
    public_url: "https://media.cybar.dev"
    jurisdiction: eu
    prefix: "site/"
    access_key_id: df7907f13e996cd4a5c9d4249be16e49
    account_id: 54ef1e8edd0606ff0103cbc93adce1c0
collections:
  - name: "blog"
    label: "Blog"
    label_singular: blog
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    sortable_fields:
      fields: ["date", "title"]
      default:
        field: date
        direction: descending
    view_filters:
      - label: Year
        field: date
        pattern: \d{4}
    view_groups:
      - label: Drafts
        field: draft
    fields:
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
