name: Optimize Images and Publish Website

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/optimize-images.yml"
      - ".github/workflows/deploy-site.yml"
      - "content/gallery/**/*.*"
      - "!content/gallery/**/*.md"

  push:
    branches: ["main"]
    paths:
      - ".github/workflows/optimize-images.yml"
      - ".github/workflows/deploy-site.yml"
      - "content/gallery/**/*.*"
      - "!content/gallery/**/*.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, cancelling others and running this instead.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: optimize
    uses: ./.github/workflows/deploy-site.yml
